import React, { useState } from "react";
import { Link } from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import ceCurriculum, { GRADES } from "../data/ceCurriculum.js";
import "./CgpaCalculator.css";

let uid = 0;
const nextId = () => ++uid;

const emptySubject = () => ({ id: nextId(), name: "", credits: "", grade: 4 });

const CgpaCalculator = () => {
  const [studentInfo, setStudentInfo] = useState({ name: "", symbol: "", reg: "" });
  const [department, setDepartment] = useState("");
  const [semesters, setSemesters] = useState([]);

  const addSemester = () => {
    setSemesters((prev) => [
      ...prev,
      { id: nextId(), name: `Semester ${prev.length + 1}`, subjects: [] },
    ]);
  };

  const removeSemester = (semId) => {
    setSemesters((prev) => prev.filter((s) => s.id !== semId));
  };

  const addSubject = (semId) => {
    setSemesters((prev) =>
      prev.map((s) =>
        s.id === semId ? { ...s, subjects: [...s.subjects, emptySubject()] } : s
      )
    );
  };

  const generateSubjects = (semId, count) => {
    const n = parseInt(count, 10);
    if (!n || n <= 0) return;
    setSemesters((prev) =>
      prev.map((s) =>
        s.id === semId
          ? { ...s, subjects: [...s.subjects, ...Array.from({ length: n }, emptySubject)] }
          : s
      )
    );
  };

  const removeSubject = (semId, subId) => {
    setSemesters((prev) =>
      prev.map((s) =>
        s.id === semId ? { ...s, subjects: s.subjects.filter((sub) => sub.id !== subId) } : s
      )
    );
  };

  const updateSubject = (semId, subId, field, value) => {
    setSemesters((prev) =>
      prev.map((s) =>
        s.id === semId
          ? {
              ...s,
              subjects: s.subjects.map((sub) =>
                sub.id === subId ? { ...sub, [field]: value } : sub
              ),
            }
          : s
      )
    );
  };

  const autofillDepartment = () => {
    if (!department) {
      alert("Please select a department first.");
      return;
    }
    if (semesters.length > 0) {
      const confirmed = window.confirm(
        "This will clear all existing semesters and autofill with Computer Engineering subjects. Continue?"
      );
      if (!confirmed) return;
    }

    const filled = ceCurriculum.map((sem) => ({
      id: nextId(),
      name: sem.name,
      subjects: sem.subjects.map((subj) => ({
        id: nextId(),
        name: subj.name,
        credits: subj.credits,
        grade: 4,
      })),
    }));
    setSemesters(filled);
  };

  // computes { credits, points, sgpa } for one semester
  const semesterStats = (sem) => {
    let credits = 0;
    let points = 0;
    sem.subjects.forEach((sub) => {
      const c = parseFloat(sub.credits);
      const g = parseFloat(sub.grade);
      if (!isNaN(c) && !isNaN(g)) {
        credits += c;
        points += c * g;
      }
    });
    return { credits, points, sgpa: credits ? points / credits : 0 };
  };

  // computes overall totals across every semester
  const overallStats = () => {
    let credits = 0;
    let points = 0;
    semesters.forEach((sem) => {
      const stats = semesterStats(sem);
      credits += stats.credits;
      points += stats.points;
    });
    return { credits, points, cgpa: credits ? points / credits : 0 };
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    const { name, symbol, reg } = studentInfo;

    doc.setFontSize(20);
    doc.text("CGPA Marksheet", 105, 20, { align: "center" });

    doc.setFontSize(12);
    doc.text(`Name: ${name || "-"}`, 14, 30);
    doc.text(`Symbol No: ${symbol || "-"}`, 14, 36);
    doc.text(`Registration No: ${reg || "-"}`, 14, 42);

    let y = 50;

    semesters.forEach((sem, i) => {
      const stats = semesterStats(sem);
      const tableData = sem.subjects.map((sub, j) => [
        j + 1,
        sub.name || "-",
        sub.credits || 0,
        GRADES.find((g) => g.value === parseFloat(sub.grade))?.label || "-",
        ((parseFloat(sub.credits) || 0) * (parseFloat(sub.grade) || 0)).toFixed(2),
      ]);

      autoTable(doc, {
        startY: y,
        head: [["S.No", "Subject", "Credits", "Grade", "Honor Points"]],
        body: tableData,
        theme: "grid",
      });

      y = doc.lastAutoTable.finalY + 5;
      doc.text(
        `${sem.name} | Credits: ${stats.credits} | Points: ${stats.points.toFixed(2)} | SGPA: ${stats.sgpa.toFixed(2)}`,
        14,
        y
      );
      y += 10;
    });

    const overall = overallStats();
    doc.text(
      `Total Credits: ${overall.credits} | Total Points: ${overall.points.toFixed(2)} | CGPA: ${overall.cgpa.toFixed(2)}`,
      14,
      y + 5
    );
    doc.setFontSize(9);
    doc.text("Generated by Niraj Bhusal", 105, 290, { align: "center" });

    doc.save("CGPA_Marksheet.pdf");
  };

  const overall = overallStats();

  return (
    <section className="cgpa-calculator" id="cgpacalculator">
      <h2 className="heading">
        <i className="fas fa-calculator"></i> CGPA <span>Calculator</span>
      </h2>
      <p className="cgpa-subtitle">
        For Pokhara University students — calculate SGPA and CGPA, semester by semester.
      </p>

      <div className="cgpa-container">
        {/* student info + department autofill */}
        <div className="cgpa-card info-card">
          <div className="cgpa-row">
            <input
              type="text"
              placeholder="Full Name"
              value={studentInfo.name}
              onChange={(e) => setStudentInfo({ ...studentInfo, name: e.target.value })}
            />
            <input
              type="text"
              placeholder="Symbol No"
              value={studentInfo.symbol}
              onChange={(e) => setStudentInfo({ ...studentInfo, symbol: e.target.value })}
            />
            <input
              type="text"
              placeholder="Registration No"
              value={studentInfo.reg}
              onChange={(e) => setStudentInfo({ ...studentInfo, reg: e.target.value })}
            />
          </div>

          <div className="dept-row">
            <label htmlFor="deptSelect">Department:</label>
            <select
              id="deptSelect"
              value={department}
              onChange={(e) => setDepartment(e.target.value)}
            >
              <option value="">-- Select Department --</option>
              <option value="CE">Computer Engineering</option>
            </select>
            <button className="autofill-btn" onClick={autofillDepartment}>
              ⚡ Autofill Subjects
            </button>
          </div>
        </div>

        {/* semester cards */}
        <div className="cgpa-grid">
          {semesters.map((sem) => {
            const stats = semesterStats(sem);
            return (
              <div className="cgpa-card" key={sem.id}>
                <button className="remove-sem" onClick={() => removeSemester(sem.id)}>
                  Remove
                </button>
                <h3>{sem.name}</h3>

                <div className="cgpa-row">
                  <input
                    type="number"
                    placeholder="No. of Subjects"
                    id={`count-${sem.id}`}
                  />
                  <button
                    className="generate-btn"
                    onClick={() =>
                      generateSubjects(sem.id, document.getElementById(`count-${sem.id}`).value)
                    }
                  >
                    Generate
                  </button>
                  <button className="add-subject-btn" onClick={() => addSubject(sem.id)}>
                    Add Subject
                  </button>
                </div>

                {sem.subjects.map((sub) => (
                  <div className="cgpa-row" key={sub.id}>
                    <input
                      type="text"
                      placeholder="Subject"
                      value={sub.name}
                      onChange={(e) => updateSubject(sem.id, sub.id, "name", e.target.value)}
                    />
                    <input
                      type="number"
                      placeholder="Credits"
                      value={sub.credits}
                      onChange={(e) => updateSubject(sem.id, sub.id, "credits", e.target.value)}
                    />
                    <select
                      value={sub.grade}
                      onChange={(e) => updateSubject(sem.id, sub.id, "grade", e.target.value)}
                    >
                      {GRADES.map((g) => (
                        <option key={g.label} value={g.value}>
                          {g.label}
                        </option>
                      ))}
                    </select>
                    <button className="remove-btn" onClick={() => removeSubject(sem.id, sub.id)}>
                      X
                    </button>
                  </div>
                ))}

                <div className="sem-result">
                  Credits: {stats.credits} | Honor Points: {stats.points.toFixed(2)} | SGPA:{" "}
                  {stats.sgpa.toFixed(2)}
                </div>
              </div>
            );
          })}
        </div>

        <div className="cgpa-actions">
          <button className="add-btn" onClick={addSemester}>
            + Add Semester
          </button>
          <button className="download-btn" onClick={downloadPDF} disabled={semesters.length === 0}>
            <i className="fas fa-download"></i> Download PDF
          </button>
        </div>

        {semesters.length > 0 && (
          <div className="final-result">
            Total Credits: {overall.credits} | Total Points: {overall.points.toFixed(2)} | CGPA:{" "}
            <strong>{overall.cgpa.toFixed(2)}</strong>
          </div>
        )}
      </div>

      <div className="cgpa-about">
        <h3>How CGPA is Calculated</h3>
        <p>
          CGPA = Total Honor Points ÷ Total Credits. This tool follows the standard grading
          system used at Pokhara University.
        </p>
      </div>

      <div className="backbtn">
        <Link to="/" className="btn">
          <i className="fas fa-arrow-left"></i>
          <span>Back to Home</span>
        </Link>
      </div>
    </section>
  );
};

export default CgpaCalculator;